set nocompatible              " be iMproved, required
filetype off                  " required
syntax on

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'


Plugin 'fatih/vim-go'
Plugin 'majutsushi/tagbar'
Plugin 'minibufexpl'
Plugin 'nerdtree'
Plugin 'pangloss/vim-javascript'
Plugin 'jeroenbourgois/vim-actionscript'
Plugin 'vim-clang-format'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

if has("autocmd")
    au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
endif
set autowrite
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set hlsearch
set incsearch
set number
set tags=tags;
"set fileencodings=utf-8
set fileencodings=utf-8,gbk,big5,gb18030,latin1
set termencoding=utf-8
set backspace=indent,eol,start

nnoremap <silent> \t :NERDTreeToggle<CR>
nnoremap <silent> \l :TagbarToggle<CR>
nnoremap <silent> \r :!r<CR>

"au FileType go,html,php,javascript inoremap <buffer> " ""<LEFT>
"au FileType go,html,php,javascript inoremap <buffer> ( ()<LEFT>
"au FileType go,html,php,javascript inoremap <buffer> [ []<LEFT>
"au FileType go,javascript inoremap <buffer> { {<CR>}<Esc>ko

let g:clang_format#auto_format=1

let g:NERDTreeWinSize=21
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:tagbar_sort = 0
let g:tagbar_width = 30
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }
set pastetoggle=<F9>
